config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'  # change to new syntax, use resources
  get 'home/index'
  get '/edit_reservations/edit/:id' => 'bicycles#edit_reservation'
  get 'bicycles/reservations_list' => 'bicycles#list', as: 'reservations_list'
  get 'bicycles/edit_reservations' => 'bicycles#edit_reservations_list', as: 'edit_reservations'
  patch 'bicycles/update' => 'bicycles#update_reservation', as: 'update_reservations_path'
  get 'bicycles/update_reservation'
  get 'bicycles/reserve' => 'bicycles#reserve', as: 'new_bicycle_event'
  get 'bicycles/reserve_for' => 'bicycles#reserve_for', as: 'new_bicycle_event_for'
  post 'bicycles/reserve/submit' => 'bicycles#create_reservation', as: 'create_bicycle_event'
  post 'bicycles/reserve_for/submit' => 'bicycles#create_reservation_for', as: 'create_bicycle_event_for'
  get 'bicycle/reserve_for'
  get 'bicycles/notice' => 'bicycles#notice', as: 'new_bicycle_event_notice'
  get 'employees/index' => 'employees#index', as: 'employees'
  get 'employees/new' => 'employees#new', as: 'new_employee'
  post 'employees/create' => 'employees#create', as: 'create_employee'
  get 'employees/edit/:id' => 'employees#edit'
  patch 'employees/edit' => 'employees#update'
  get 'employees/reserve'
  get 'employees/update'
  get 'employees/notice'
  devise_scope :employee do
    get 'sign_out', to: 'devise/sessions#destroy', as: 'sign_out'
  end

  devise_for :employees, path: '/'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bicycle.rb
class Bicycle < ApplicationRecord
  has_many :bicycle_events
  validates_presence_of :model
end

app/models/bicycle_event.rb
class BicycleEvent < ApplicationRecord
  belongs_to :bicycle
  belongs_to :employee
  validates_presence_of :started, :finished
  validates_uniqueness_of :started, scope: :bicycle_id


  def bike_taken?
    (started..finished).include? Time.now
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :bicycle_events
  devise :database_authenticatable, :registerable
  validates_presence_of :name, :surname, :email, :encrypted_password
  validates_uniqueness_of :email

  def is_admin?
    is_admin == true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
  before_action :authenticate_employee!
  def new; end

  def create; end

  def update; end

  def list
    @bicycles = Bicycle.all
    @events = BicycleEvent.all
  end

  def reserve
    @bicycles = Bicycle.all
    @event = BicycleEvent.new
    @events = BicycleEvent.all
  end

  def reserve_for
    @employees = Employee.all
    @bicycles = Bicycle.all
    @event = BicycleEvent.new
    @events = BicycleEvent.all
  end

  def create_reservation_for
    @event = Bicycle.where(id: event_params[:bicycle_id].to_i)
      .first
      .bicycle_events
      .new(event_params)
    @events = BicycleEvent.where(bicycle_id: @event.bicycle_id)
    @event.save unless check_event_availability(@events, event_params) == false
    render 'notice'
  end

  def create_reservation
    @event = Bicycle.where(id: event_params[:bicycle_id].to_i)
      .first
      .bicycle_events
      .new(event_params.merge(employee_id: current_employee.id))
    @events = BicycleEvent.where(bicycle_id: @event.bicycle_id)
    @event.save if (check_event_availability(@events, event_params) == false)
    render 'notice'
  end

  def edit_reservations_list
    @events = BicycleEvent.all
    @employees = Employee.all
  end

  def edit_reservation
    @event = BicycleEvent.find(params[:id])
    @employees = Employee.all
  end

  def update_reservation
    @event = BicycleEvent.find(event_params[:id])
    events = BicycleEvent.where(bicycle_id: @event.bicycle_id)
    if check_event_availability(events, event_params) == false
      flash[:notice] = 'Event not updated - it overlaps with other event for this bicycle'
      redirect_to edit_reservations_path
    else
      @event.update(event_params)
      flash[:notice] = 'Event sucessfully updated'
      redirect_to edit_reservations_path
    end
  end

  private

  def event_params
    params.require(:bicycle_event).permit(:id, :started, :finished, :bicycle_id, :employee_id)
  end

  def check_event_availability(events, event_params)
    possible_event = BicycleEvent.new(event_params)
    possible_event_times = possible_event.started..possible_event.finished
    events.each do |event|
      time_available = event.started..event.finished
      if time_available.include? possible_event_times
        break
        return false
      else
        return true
      end
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_employee!
  before_action :is_admin?

  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def create
    pass = BCrypt::Password.create(employee_params[:encrypted_password])
    @employee = Employee.new(employee_params.merge(encrypted_password: pass))
    @employee.save
    render 'notice'
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:employee][:id])
    @employee.update(employee_params.except(:encrypted_password, :id))
    flash[:notice] = 'Employee updated'
    flash[:notice] = 'Update failed' unless @employee.update(employee_params.except(:encrypted_password, :id))
    redirect_to employees_path
  end

  private

  def employee_params
    params.require(:employee).permit(:id, :name, :surname, :email, :encrypted_password)
  end

  def is_admin?
    redirect_to root_path unless current_employee.is_admin?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_employee!
  def index
    @bicycles = Bicycle.all
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bicycles/_list.html.erb
<section class="hero is-primary is-fullheight">
  <div class="hero-body">
    <div class="container">
      <center>
        <select id="list" onchange="filters()" class='form-control'>
          <option value="" placeholder="option">Select Model</option>
          <%@bicycles.each do |cycle| %>
          <option value="<%=cycle.model%>"><%=cycle.model%></option>
          <%end%>
        </select>

        <table id="Table" class="table">
          <thead>
            <tr>
              <th><abbr title="Bicycle">Bicycle model</abbr></th>
              <th><abbr title="Manager">Employee</abbr></th>
              <th><abbr title="Started">Reservation start</abbr></th>
              <th><abbr title="Won">Reservation end</abbr></th>
            </tr>
            <% @events.each do |events| %>
            <tr>
              <td><%=events.bicycle.model%></td>
              <td><%="#{events.employee.name}" + " #{events.employee.surname}" %></td>
              <td><%=events.started%></td>
              <td><%=events.finished%></td>
            </tr>
            <%end%>
        </table>
    </div>

    </center>
  </div>
  </div>
</section>

<script>
function filters() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("list");
  filter = input.value.toUpperCase();
  table = document.getElementById("Table");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>

app/views/bicycles/_reserve_form.html.erb
<section class="hero is-primary is-fullheight">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-5-tablet is-4-desktop is-3-widescreen">

          <input type="hidden" id="timezone" name="timezone" value="+02:00">

          <% if current_page?(action: 'reserve_for') %>

          <form class="box" id="new_bicycle_event" action="/bicycles/reserve_for/submit" accept-charset="UTF-8"
            method="post">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <%=image_tag("bikegif.gif")%>

            <select name="bicycle_event[employee_id]" id="bicycle_event_employee_id">
              <%@employees.each do |employee| %>
              <option value="<%=employee.id%>"><%= "#{employee.name}" + " #{employee.surname}"%></option>
            <% end %>
            </select><br /><br />

          <% else %>

            <form class="box" id="new_bicycle_event" action="/bicycles/reserve/submit" accept-charset="UTF-8"
              method="post">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <%=image_tag("bikegif.gif")%>

          <% end %>

              <label for="bicycle_event_started">Start of usage</label>

              <input type="datetime-local" id="bicycle_event_started" name="bicycle_event[started]"
                value="<%= DateTime.now %>" min="<%= Time.now.strftime("%Y-%m-%dT%H:%M") %>" max=""><br /><br />

              <input type="datetime-local" id="bicycle_event_finished" name="bicycle_event[finished]"
                value="<%= DateTime.now %>" min="<%= Time.now.strftime("%Y-%m-%dT%H:%M") %>" max=""> <br /><br />

              <select name="bicycle_event[bicycle_id]" id="bicycle_event_bicycle_id">
                <%@bicycles.each do |bicycle| %>
                <option value="<%=bicycle.id%>"><%= bicycle.model %></option>
                <% end %>
              </select><br /><br />
              <input type="submit" name="commit" value="Reģistrēties" data-disable-with="Reģistrēties">
            </form>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/bicycles/edit_reservation.html.erb
<section class="hero is-primary is-fullheight">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-5-tablet is-4-desktop is-3-widescreen">

          <input type="hidden" id="timezone" name="timezone" value="+02:00">

          <form class="box" id="edit_bicycle_event" action="/bicycles/update_reservation" accept-charset="UTF-8"
            method="patch">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <%=image_tag("bikegif.gif")%>

            <input autofocus="autofocus" type="hidden" name="bicycle_event[id]" id="bicycle_event_id"
              value="<%=@event.id%>">

            <label for="bicycle_event_started">Start of usage</label>

            <input type="datetime-local" id="bicycle_event_started" name="bicycle_event[started]"
              value="<%= @event.started %>" min="<%= Time.now.strftime("%Y-%m-%dT%H:%M") %>" max=""><br /><br />

            <input type="datetime-local" id="bicycle_event_finished" name="bicycle_event[finished]"
              value="<%= @event.started %>" min="<%= Time.now.strftime("%Y-%m-%dT%H:%M") %>" max=""> <br /><br />

            Change bicycle or employee: <input type="checkbox" id="Check" onclick="enable()">

            <select name="bicycle_event[bicycle_id]" id="bicycle_event_bicycle_id" disabled>
              <option value="<%@event.bicycle.id%>"><%= @event.bicycle.model %></option>
            </select>

            <select name="bicycle_event[employee_id]" id="bicycle_event_employee_id" disabled>
              <option value="<%@event.employee.id%>"><%= @event.employee.name %></option>
              <%@employees.each do |employee| %>
              <option value="<%@event.bicycle.id%>"><%= @event.bicycle.model %></option>
              <%end%>
            </select>

            <input type="submit" name="commit" value="Reģistrēties" data-disable-with="Reģistrēties">
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

<script>
  function enable() {
    var checkBox = document.getElementById("Check");
    var bicycle = document.getElementById("bicycle_event_bicycle_id");
    var employee = document.getElementById("bicycle_event_employee_id");

    if (checkBox.checked == true) {
      bicycle.disabled = false;
      employee.disabled = false
    }

    if (checkBox.checked == false) {
      bicycle.disabled = true;
      employee.disabled = true
    }
  }
</script>

app/views/bicycles/edit_reservations_list.html.erb
<section class="hero is-primary is-fullheight">
  <div class="hero-body">
    <div class="container">
        <center>
          <select id="list" onchange="filters()" class='form-control'>
            <option value="" placeholder="option">Select Employee</option>
            <%@employees.each do |employee| %>
            <option value="<%=employee.id%>"><%=employee.name%></option>
            <%end%>
          </select>

            <table id="Table" class="table">
              <thead>
                <tr>
                  <th><abbr title="Model">Model</abbr></th>
                  <th><abbr title="Started">Reservation start</abbr></th>
                  <th><abbr title="Finished">Reservation end</abbr></th>
                </tr>
                 <% @employees.each do |employee| %>
                 <% employee.bicycle_events.each do |event| %>
                <tr>
                <td style="display:none;"><%=event.employee.id%></td>
                  <td><%=event.bicycle.model%></td>
                  <td><%=event.started%></td>
                  <td><%=event.finished%></td>
                  <td><a href="/edit_reservations/edit/<%=event.id%>">Edit</a><td>
                  </tr>
                  <%end%>
                  <%end%>
            </table>
          </div>

</center>
    </div>
  </div>
</section>

<script>
function filters() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("list");
  filter = input.value.toUpperCase();
  table = document.getElementById("Table");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>

app/views/bicycles/list.html.erb
<%= render 'list' %>

app/views/bicycles/notice.html.erb
<section class="hero is-primary is-fullheight">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-5-tablet is-4-desktop is-3-widescreen">
          <div class="box">
            <%if @event.save%>
            <center>
              <%=image_tag("success.jpg")%>
              <br>
              <br>
              <h3><strong>Success!</strong></h3>
            </center>
            <br>
            <br>
            <div class="columns">
              <div class="column">
                <a class="button is-success" href="<%= reservations_list_path %>">
                  Back to list
                </a>
              </div>
              <div class="column">
                <a class="button is-success" href="<%= new_bicycle_event_path %>">
                  Create another
                </a>
              </div>
            </div>
            <%else%>
            <center>
              <%=image_tag("not_success.jpg")%>
              <br>
              <br>
              <h3><strong>Adding reservation failed! Reservation for these times already exists! Check reservations <a
                    href="<%=reservations_list_path %>">schedule</a> before making a reservation!</strong></h3>
            </center>
            <br>
            <br>
            <div class="columns">
              <div class="column">
                <a class="button is-success" href="<%= reservations_list_path %>">
                  Back to list
                </a>
              </div>
              <div class="column">
                <a class="button is-success" href="<%= new_bicycle_event_path %>">
                  Try again
                </a>
              </div>
            </div>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/bicycles/reserve.html.erb
<%= render 'reserve_form' %>

app/views/bicycles/reserve_for.html.erb
<%= render 'reserve_form' %>

app/views/employees/create.html.erb
<h1>Employees#create</h1>
<p>Find me in app/views/employees/create.html.erb</p>

app/views/employees/edit.html.erb
<section class="hero is-primary is-fullheight">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-5-tablet is-4-desktop is-3-widescreen">
          <form class="box" id="update_employee" action="/employees/update" accept-charset="UTF-8" method="patch"><input
              type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <div><label for="employee_id">Name</label><br>

              <input autofocus="autofocus" type="hidden" name="employee[id]" id="employee_id"
                value="<%=@employee.id %>">
            </div>
            <div><label for="employee_name">Name</label><br>

              <input autofocus="autofocus" type="text" name="employee[name]" id="employee_name"
                value="<%=@employee.name%>">
            </div>
            <br>
            <div><label for="employee_surname">Surname</label><br>

              <input autofocus="autofocus" type="text" name="employee[surname]" id="employee_surname"
                value="<%=@employee.surname%>">
            </div>
            <br>
            <div><label for="employee_email">Email</label><br>

              <input autofocus="autofocus" type="email" name="employee[email]" id="employee_email"
                value="<%=@employee.email%>">
            </div>

            <br>
            <br>

            <input type="submit" name="commit" value="Update employee" data-disable-with="Submit">
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/employees/index.html.erb
<section class="hero is-primary is-fullheight">
  <div class="hero-body">
    <div class="container">

      <center>

        <thead>
          <table id="myTable" class="table">
            <tr>
              <th><abbr title="Employee name">First Name</abbr></th>
              <th><abbr title="Employee last name">Last Name</abbr></th>
              <th><abbr title="e-mail">e-mail</abbr></th>
              <th><abbr title="e-mail">Actions</abbr></th>
              <th><abbr title="e-mail"> <a class="button is-success" href="/employees/new">
                    Create employee
                  </a></abbr></th>


            </tr>
            <% @employees.each do |employee| %>
            <tr>
              <td style="display:none;"><%=employee.id%></td>
              <td><%=employee.name%></td>
              <td><%=employee.surname%></td>
              <td><%=employee.email%></td>
              <td><a href="/employees/edit/<%=employee.id%>">Edit</a>
              <td>
            </tr>
            <%end%>
          </table>
    </div>

    </center>
  </div>
  </div>
</section>

app/views/employees/new.html.erb
<section class="hero is-primary is-fullheight">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-5-tablet is-4-desktop is-3-widescreen">
          <form class="box" id="new_employee" action="/employees/create" accept-charset="UTF-8" method="post"><input
              type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <div><label for="employee_name">Name</label><br>
              *
              <input autofocus="autofocus" type="text" name="employee[name]" id="employee_name">
            </div>
            <br>
            <div><label for="employee_surname">Surname</label><br>
              *
              <input autofocus="autofocus" type="text" name="employee[surname]" id="employee_surname">
            </div>
            <br>
            <div><label for="employee_email">Email</label><br>
              *
              <input autofocus="autofocus" type="email" name="employee[email]" id="employee_email">
            </div>
            <br>
            <div><label for="employee_password">Password</label><br>
              *
              <input autofocus="autofocus" type="text" name="employee[encrypted_password]"
                id="employee_encrypted_password">
            </div>
            <br>
            <br>

            <input type="submit" name="commit" value="Create employee" data-disable-with="Submit">
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/employees/notice.html.erb
<section class="hero is-primary is-fullheight">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-5-tablet is-4-desktop is-3-widescreen">
          <div class="box">
            <%if @employee.save%>
            <center>
              <%=image_tag("success_form.jpeg")%>
              <br>
              <br>
              <h3><strong>Success!</strong></h3>
            </center>
            <br>
            <br>
            <div class="columns">
              <div class="column">
                <a class="button is-success" href="/employees/index">
                  Back to list
                </a>
              </div>
              <div class="column">
                <a class="button is-success" href="/employees/new">
                  Add another
                </a>
              </div>
            </div>
            <%else%>
            <center>
              <%=image_tag("warning.png")%>
              <br>
              <br>
              <h3><strong>Adding employee failed! Perhaps and employee with such e-mail already exists in system, or you
                  forgot to fill some field! </strong></h3>
            </center>
            <br>
            <br>
            <div class="columns">
              <div class="column">
                <a class="button is-success" href="/employees/index">
                  Back to list
                </a>
              </div>
              <div class="column">
                <a class="button is-success" href="/employees/new">
                  Try again
                </a>
              </div>
            </div>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/employees/update.html.erb
<h1>Employees#update</h1>
<p>Find me in app/views/employees/update.html.erb</p>

app/views/home/index.html.erb
<% is_taken = "" %>
<% current_event = "" %>

<section class="hero is-primary is-fullheight">
 <div class="hero-body">
<div class="container">
<center>

<div class="columns">
  <div class="column">
  <div class= "box">
   <a href="<%=reservations_list_path%>"><%=image_tag("schedule.png")%></a>
    Schedule of reservations
    </div>
  </div>
  <div class="column">
    <div class= "box">
  <a href="<%=new_bicycle_event_path%>"><%=image_tag("reservation.png")%></a>
    Reservation for myself
    </div>
  </div>
  <div class="column">
    <div class= "box">
  <a href="<%=new_bicycle_event_for_path%>"><%=image_tag("bicycle.jpg")%></a>
    Reservation for employee
    </div>
  </div>
  <%if current_employee.is_admin?%>
  <div class="column">
  <div class= "box">
  <a href="<%=edit_reservations_path%>"><%=image_tag("edit_reservation.jpg")%></a>
    Edit reservations
  </div>
  </div>
  <div class="column">
  <div class= "box">
  <a href="<%=employees_path%>"><%=image_tag("manager.png")%></a>
    Employees
  </div>
  </div>
  <%end%>
</div>

<center>
<table id="index" class="table">
  <thead>
    <tr>
      <th><abbr title="Model">Bicycle model</abbr></th>
      <th><abbr title="Times">Times reserved:</abbr></th>
      <th><abbr title="Availability">Available now?</abbr></th>
      <th><abbr title="Next">Available for next reservation at:</abbr></th>
    </tr>

    <% @bicycles.each do |cycle| %>
      <%cycle.bicycle_events.each do |event|%>
        <% current_event = event %>
        <% is_taken = event.bike_taken? %>
          <%if is_taken %>
          <%break%>
        <%else%>
          <% is_taken %>
        <%end%>
      <%end%>
      <tr>
        <td><%= cycle.model %></td>
        <td><%= cycle.bicycle_events.count %></td>
        <%if is_taken == false %>
          <td>Yes!</td>
        <%else%>
          <td>No (current user: <%= "#{current_event.employee.name}" + " #{current_event.employee.surname}" %>)</td>
        <%end%>
        <%if is_taken %>
          <td><%=current_event.finished%></td>
        <%else%>
          <td>Available now!</td>
        <%end%>
      </tr>
    <%end%>
  </table>
  </center>
  </center>
  </div>
  </div>
  </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Bicycles</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all' %>
</head>

<body>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <img src="https://image.flaticon.com/icons/png/512/130/130066.png" width="40" height="190">
      </a>
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
        data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
      </div>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a class="button is-success" href="/">
            Home
          </a>
          <a class="button is-light" href="/sign_out">
            Sign out
          </a>
        </div>
      </div>
    </div>
    </div>
  </nav>
       <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "notification is-primary" %>
  <% end %>
  <%= yield %>
</body>

</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bicycles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css'>
  <body>
    <%= yield %>
  </body>
</html>